branches:
  only:
    - master
    - develop-0.1
language: python
python:
  - "3.7"
# install:
  # - pip install -r requirements.txt
script:
  - python -m unittest tests.linux.test_canda_linux.CandaCoreTest
