environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x" # currently 3.7.4
      PYTHON_ARCH: "64"

build: off

install:
- pip install -r requirements.txt

test_script:
-  python -m unittest discover -s tests/windows
